### ISSUE TITLE
Can't find "Api Url"

### ISSUE THREAD

**Issue by bigboss97lnt** [rishigupta121/conversion-api-tiktok#2]
Hello, I've been trying to use your extensions, I got the pixel id and the access code, but I can't find the API URL

@rishigupta121 Please help! :D

**Comment by rishigupta121** [comment]
Hello, In Api url you can put "https://business-api.tiktok.com/open_api/v1.2/pixel/track/"

**Comment by bigboss97lnt** [comment]
Yeah I figured that out after reading the documentation, even after adding all required fields the plugin wasn't working until I commented the test_code from the payload, check my commit on the fork i did

**Comment by rishigupta121** [comment]
Have you tried with debug mode No.

**Comment by bigboss97lnt** [comment]
Yes, but it keeps sending it as test for some reason
